service: dynamodb-crud-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postTableName}

custom:
  postTableName: post-table-${self:custom.postTableName}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: api.getPost
    name: get-post
    memorySize: 128 #mb
    timeout: 5 #seconds
    events:
      - http:
          path: post/{postId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resources: !GetAtt PostTable.Arn
  createPost:
    handler: api.createPost
    name: create-post
    memorySize: 128 #mb
    timeout: 5
    events:
      - http:
          path: post
          method: POST
    iamRolesStatements:
      - Effects: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostTable.Arn
  updatePost:
    handler: api.updatePost
    name: update-post
    memorySize: 128 #mb
    timeout: 5
    events:
      - http:
          path: post/{postId}
          method: PUT
    iamRolesStatements:
      - Effects: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostTable.Arn
  deletePost:
    handler: api.deletePost
    name: delete-post
    memorySize: 128 #mb
    timeout: 5
    events:
      - http:
          path: post/{postId}
          method: DELETE
    iamRolesStatements:
      - Effects: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt PostTable.Arn
  getAllPost:
    handler: api.getAllPosts
    name: get-all-posts
    memorySize: 128 #mb
    timeout: 5
    events:
      - http:
          path: posts
          method: GET
    iamRolesStatements:
      - Effects: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostTable.Arn
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom:postTableName}
        AttributesDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - Attributes: postId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
